[package]
name = "todo"
version = "0.1.0"
authors = ["DiscoBiscuit99 <creme3sandwich@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.5"
term_cursor = "0.2.1"
